{% set name = "uavro" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uavro-{{ version }}.tar.gz
  sha256: 4c26012b9218ae07e81573958331c24a77e8964556fc768223aae4f11b647cdf

build:
  number: 1004
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - pip
    - msinttypes  # [win]
  run:
    - python
    - pandas
    - cython
    - fastparquet
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - uavro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/martindurant/uavro
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Very fast avro file to dataframe reader'

extra:
  recipe-maintainers:
    - martindurant
