{% set name = "uavro" %}
{% set version = "0.1.2" %}
{% set sha256 = "4c26012b9218ae07e81573958331c24a77e8964556fc768223aae4f11b647cdf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - pip
    - msinttypes  # [win]
  run:
    - python
    - pandas
    - fastparquet

test:
  imports:
    - uavro

about:
  home: https://github.com/martindurant/uavro
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Very fast avro file to dataframe reader'

extra:
  recipe-maintainers:
    - martindurant
