travis:
  secure:
    BINSTAR_TOKEN: o7+MnsIIayt140FT9esMhzFFX2rJ443fJZkU5gYw9Z1FMJ0SpYxqeDOjgNW/5jb0W0DnJ2j7S9R0zvbaAGA7a/nVS22rx+bAKrOQEv1r4FcDqbn7/9qACpjz4pEgAq/TUrC2JoMkRjaUD5K6XJsRcL09mMLHBdl6ntK2e4qnqu0eTn8rQy43itRLR4WYF8KcschpyZjmL20WzYbcjUVpzkOuxL7AWcgt9IdxmiDRjClBk9O2aW0ctFsYwQ3Xfpyu94gYRLL1BMfotQM4Gtv2LcisyZF8bDy1vsirEuqgfIYr4/5BMeyhZxZFwn1Z1QDaoIvaqgUu3daibFWL6FjYOe7I/N7QE4L1PGcSRZcgUqmvxYAhPnO8EfaG7fhRr0NobsIWGSXmMkiag9hgyo110P/TCwbKWQl+Lhlgh1O4qXrMauG7cWLy20dvCGNvuU+/JTyyS9vRl1gXfdQK8PYy3xLX/md0ugK37PGbP01C14WiM9hgfN3W5TAxS066dbpOK7vsBBw1eiOpVh6ufPDAPYWBjkAQPBVbmnTIHhk2lD0Y/9IGqd8tcuHm2O4IN/b5xUB32kKKDvJXSJ/JFdGt+AeCQj59VbjlTlWQgWBIGGr9QUJF3omxShAiTDcbF0cH/6qKDU7h6hTUtKjZ8GmzI4VmOk1E8mOr/NpFMAh8Skc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
